In [2]:
import numpy as np

In [5]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [6]:
b = np.array([[4, 5, 6],[7, 8, 9]])
print(b)

[[4 5 6]
 [7 8 9]]


In [13]:
#Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [11]:
#Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [12]:
#Get Type
a.dtype

dtype('int32')

## *Accessing/Changing Specific Elements, Rows, and Columns*

In [30]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]], dtype=object)
print(a)
print(a.shape)

[[1 2 3 4 5 6 7]
 [8 9 10 11 12 13 14]]
(2, 7)


In [33]:
#Get a Specific Element
a[1,5]
a[1,-2]

13

In [34]:
#Get a Specific Row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7], dtype=object)

In [36]:
#Get a specifc Column
a[:, 2]

array([3, 10], dtype=object)

In [39]:
#Getting a little more fancy [start_index:stop_index:step_size]
a[0, 1:6:2]

array([2, 4, 6], dtype=object)

In [41]:
a[1,5] = 20
print(a)

a[:, 2] = [1,2]
print(a)

[[1 2 3 4 5 6 7]
 [8 9 10 11 12 20 14]]
[[1 2 1 4 5 6 7]
 [8 9 2 11 12 20 14]]


_3D Example_

In [49]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [50]:
b[0,1,1]

4

In [52]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

## *Initializing Different Type of Arrays*

In [53]:
#All 0's matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [54]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [55]:
#All 1's matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [56]:
#Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [57]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.90276196, 0.58858354],
       [0.23312464, 0.67961431],
       [0.55372937, 0.24776374],
       [0.46404678, 0.3897775 ]])

In [58]:
#Random Integer Numbers
np.random.randint(7, size=(3,3))

array([[1, 4, 3],
       [1, 5, 2],
       [3, 4, 2]])

In [59]:
#The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
#Be careful when copying arrays
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


## Mathematics

In [94]:
a = np.array([1,2,3,4])
b = a.copy()
b = np.array([b])
b = b.T
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [64]:
a + 2

array([3, 4, 5, 6])

In [65]:
a - 2

array([-1,  0,  1,  2])

In [66]:
a*2

array([2, 4, 6, 8])

In [67]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [68]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [69]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [70]:
#Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

## Linear Algebra

In [72]:
#Matrix Multiplication
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [76]:
#Finding Determinant
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [96]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.inner(a,b))

32


In [39]:
kernel = np.array([    [1,4,6,4,1],
    [4,16,24,16,4],
    [6,24,36,24,6],
    [4,16,24,16,4],
    [1,4,6,4,1]
])

u, s, v = np.linalg.svd(kernel)

# array_1 = U
# array_2 = S
# array_3 = V
# array_1 = U[:, 0]
# array_2 = V[0, :]
k1 = u[:,0,None] * np.sqrt(s[0])
k2 = v[None,0,:] * np.sqrt(s[0])

k1 = np.round(k1.transpose()).astype(int).T
k2 = np.round(k2.transpose()).astype(int).T
# print(array_1.shape)
# print(array_1, "\n")
print(k1.shape)
print(k1, "\n")
print(k2.shape)
print(k2, "\n")
print(k1*k2)

# Verify that the product of the two arrays is equal to the original kernel
# assert np.allclose(np.outer(array_1, array_2), kernel)

(5, 1)
[[-1]
 [-4]
 [-6]
 [-4]
 [-1]] 

(1, 5)
[[-1 -4 -6 -4 -1]] 

[[ 1  4  6  4  1]
 [ 4 16 24 16  4]
 [ 6 24 36 24  6]
 [ 4 16 24 16  4]
 [ 1  4  6  4  1]]
